name: Main

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "*.md"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
        config:
          - { name: "🍏 macOS Clang", os: macos-latest }
          - { name: "🐧 Linux GCC", os: ubuntu-latest }
          - { name: "🪟 Windows MinGW", os: windows-latest }

    name: 🛠 Build / ${{ matrix.config.name }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies (macOS)
        if: matrix.config.os == 'macos-latest'
        run: brew install ccache ninja

      - name: Install Dependencies (Linux)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache ninja-build

      - name: Install Dependencies (Windows)
        if: matrix.config.os == 'windows-latest'
        run: |
          choco install mingw
          choco install ninja
          choco install ccache

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "10G"
          key: ${{ matrix.config.os }}-${{ matrix.build_type }}

      - name: Configure
        run: |
          mkdir -p GDExtension-build
          cmake -B GDExtension-build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .

      - name: Build
        run: cmake --build GDExtension-build

      - name: Upload artifact (Debug - Linux)
        if: matrix.config.os == 'ubuntu-latest' && matrix.build_type == 'Debug'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-Debug-Linux
          path: ${{ github.workspace }}/GDExtension-build/libgodot-riscv.so

      - name: Upload artifact (Debug - macOS)
        if: matrix.config.os == 'macos-latest' && matrix.build_type == 'Debug'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-Debug-macOS
          path: ${{ github.workspace }}/GDExtension-build/libgodot-riscv.dylib

      - name: Upload artifact (Debug - Windows)
        if: matrix.config.os == 'windows-latest' && matrix.build_type == 'Debug'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-Debug-Windows
          path: ${{ github.workspace }}/GDExtension-build/libgodot-riscv.dll

      - name: Upload artifact (Release - Linux)
        if: matrix.config.os == 'ubuntu-latest' && matrix.build_type == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-Release-Linux
          path: ${{ github.workspace }}/GDExtension-build/libgodot-riscv.so

      - name: Upload artifact (Release - macOS)
        if: matrix.config.os == 'macos-latest' && matrix.build_type == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-Release-macOS
          path: ${{ github.workspace }}/GDExtension-build/libgodot-riscv.dylib

      - name: Upload artifact (Release - Windows)
        if: matrix.config.os == 'windows-latest' && matrix.build_type == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-Release-Windows
          path: ${{ github.workspace }}/GDExtension-build/libgodot-riscv.dll
